version: "3"
  services:
    mevuun_backend:
      image: mdsantos/mevuun
      deploy:
        replicas: 5
      resources: 
        limits:
        cpus: "0.1"
        memory: 500M
      restart_policy:
        condition: on-failure
      ports:
      - "3000:3000"

